### ISSUE TITLE
64 Bit Version?

### ISSUE THREAD

**Issue by atatassault** [PlumberTaskForce/Datamining-Guide#3]
Tried using this, but apparently its in 32bit, and windows command prompt gave an error when using export.schemas about a 32 bit program not being able to access data from a 64bit program. Can we get a 64bit version of this tool?

**Comment by Jff007** [comment]
Hey, atat, nice seeing you here! So, that aspect relies on Rick updating his tools, so hop on over to his gibbed.cryptic repo for updates on that.

**Comment by ghostlyghastly** [comment]
Same problem for Neverwinter

```Gibbed.Cryptic.ExportSchemas.exe

Unhandled Exception: System.ComponentModel.Win32Exception: A 32 bit processes cannot access modules of a 64 bit process.
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at Gibbed.Cryptic.ExportSchemas.Program.FindSuitableProcess(String& projectName)
   at Gibbed.Cryptic.ExportSchemas.Program.Main(String[] args)```

**Comment by Relm0re** [comment]
same
